version: "2"
services:
#  nginx:
#    build: nginx
#    ports:
#      - "80:80"
#    environment:
#      REVERSE_PROXY_DOMAIN_NAME: ${REVERSE_PROXY_DOMAIN_NAME}
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: toread
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
  redis:
     image: redis
     volumes:
      - redis-data:/data
  gitlabce:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.devops.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.devops.com';
        gitlab_rails['gitlab_shell_ssh_port'] = 2280;
        gitlab_rails['gitlab_email_from'] = 'gitlab@devpt.ltd';
        gitlab_rails['smtp_enable'] = true;
        gitlab_rails['smtp_address'] = "smtp.devpt.ltd";
        gitlab_rails['smtp_port'] = 25;
        gitlab_rails['smtp_user_name'] = "gitlab@devpt.ltd";
        gitlab_rails['smtp_password'] = "Qeer1234";
        gitlab_rails['smtp_domain'] = "devpt.ltd";
        gitlab_rails['smtp_authentication'] = "login";
        gitlab_rails['db_adapter'] = "postgresql";
        gitlab_rails['db_encoding'] = "unicode";
        gitlab_rails['db_collation'] = nil;
        gitlab_rails['db_database'] = "gitlab";
        gitlab_rails['db_pool'] = 10;
        gitlab_rails['db_username'] = "gitlab";
        gitlab_rails['db_password'] = "gitlab";
        gitlab_rails['db_host'] = "postgres";
        gitlab_rails['db_port'] = 5432;
        gitlab_rails['db_prepared_statements'] = true;
        gitlab_rails['db_statements_limit'] = 1000;
        gitlab_rails['redis_host'] = "redis";
        gitlab_rails['redis_port'] = 6379;
        gitlab_rails['redis_password'] = nil;
        gitlab_rails['redis_database'] = 0;
    ports:
      - '80:80'
      - '443:443'
      - '2280:2280'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
#  mattermost:
#    image: mattermost/mattermost-prod-app:3.9.0
#    environment:
#      MATTERMOST_ENABLE_SSL: "true"
#      DB_HOST: postgres
#      MM_USERNAME:  mattermost
#      MM_PASSWORD:  mattermost
#      MM_DBNAME: mattermost
#    ports:
#      - 9999:80
#    volumes:
#      - mattermost-data:/mattermost/data
#      - mattermost-config:/mattermost/config
#  owncloud:
#    image: owncloud
#    volumes:
#      - owncloud-data:/var/www/html/data
#      - owncloud-config:/var/www/html/config
#      - owncloud-apps:/var/www/html/apps
#  ldap:
#    image: osixia/openldap
#    volumes:
#      - ldap-data:/var/lib/ldap
#      - ldap-config:/etc/ldap/slapd.d
#    ulimits:
#      nofile:
#        soft: 65536
#        hard: 65536

volumes:
  gitlab-config:
    driver: local
  gitlab-logs:
    driver: local
  gitlab-data:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local
#  mattermost-data:
#    driver: local
#  mattermost-config:
#    driver: local
#  owncloud-data:
#    driver: local
#  owncloud-config:
#    driver: local
#  owncloud-apps:
#    driver: local
#  ldap-data:
#    driver: local
#  ldap-config:
#    driver: local
