version: "2"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: toread
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mattermost:
    image: mattermost/mattermost-prod-app:3.9.0
    environment:
      MATTERMOST_ENABLE_SSL: "true"
      DB_HOST: postgres
      DB_PORT_NUMBER:
      MM_USERNAME:  mattermost
      MM_PASSWORD:  mattermost
      MM_DBNAME: mattermost
      APP_PORT_NUMBER: 9090
      ports:
        - 9090:9090
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-config:/mattermost/config
#  owncloud:
#    image: owncloud
#    volumes:
#      - owncloud-data:/var/www/html/data
#      - owncloud-config:/var/www/html/config
#      - owncloud-apps:/var/www/html/apps
#  ldap:
#    image: osixia/openldap
#    volumes:
#      - ldap-data:/var/lib/ldap
#      - ldap-config:/etc/ldap/slapd.d
#    ulimits:
#      nofile:
#        soft: 65536
#        hard: 65536

volumes:
  postgres-data:
    driver: local
  mattermost-data:
    driver: local
  mattermost-config:
    driver: local
#  owncloud-data:
#    driver: local
#  owncloud-config:
#    driver: local
#  owncloud-apps:
#    driver: local
#  ldap-data:
#    driver: local
#  ldap-config:
#    driver: local
