version: "2"
services:
#  nginx:
#    build: nginx
#    ports:
#      - "80:80"
#    environment:
#      REVERSE_PROXY_DOMAIN_NAME: ${REVERSE_PROXY_DOMAIN_NAME}
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: toread
  redis:
     image: redis
     volumes:
      - redis-data:/data
  gitlabce:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #阿里云服务器推送处理
        gitlab_rails['gitlab_email_from'] = 'gitlab@devpt.ltd'
        gitlab_rails['gitlab_email_reply_to'] = 'gitlab@devpt.ltd'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.devpt.ltd"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "gitlab@devpt.ltd"
        gitlab_rails['smtp_password'] = "Qwer1234"
        gitlab_rails['smtp_domain'] = "devpt.ltd"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        #配置数据
        # Disable the built-in Postgres
        postgresql['enable'] = false
        # Fill in the connection details for database.yml
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab'
        #redis配置
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = nil
        gitlab_rails['redis_database'] = 0
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
  openldap:
    image: osixia/openldap
    volumes:
      - ldap-config:/etc/ldap/slapd.d
      - ldap-database:/var/lib/ldap
    environment:
      LDAP_ORGANISATION: "devpt.ltd"
      LDAP_DOMAIN: "devpt.ltd"
      LDAP_ADMIN_PASSWORD: "toread"
  ldap-account-manager:
    image: jkpark/docker-ldap-account-manager
    volumes:
    - ldap-account-config: /config
    ports:
    - "20080:80"
volumes:
  ldap-account-config:
    driver: local
  ldap-config:
    driver: local
  ldap-database:
    driver: local
  gitlab-config:
    driver: local
  gitlab-logs:
    driver: local
  gitlab-data:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local
#  mattermost-data:
#    driver: local
#  mattermost-config:
#    driver: local
#  owncloud-data:
#    driver: local
#  owncloud-config:
#    driver: local
#  owncloud-apps:
#    driver: local
#  ldap-data:
#    driver: local
#  ldap-config:
#    driver: local
